version: '3.7'

networks:
  docker_base_service:
    external: false
    name: docker_base_service
volumes:
  portainerdata:
    name: portainerdata
services:
# docker 可视化管理
  portainer:                         
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    ports:         
      - 9910:9000                              
    volumes:                                     
      - /var/run/docker.sock:/var/run/docker.sock      
      - portainerdata:/data
    networks:
      - docker_base_service      

# 内网穿透
  nps_server:                         
    image: oldiy/nps-server
    container_name: nps_server
    restart: always
    ports:         
      - 9911:8080                              
      - 9912:8284                              
      - 9913:8024                              
    networks:
      - docker_base_service   
    volumes:                                     
      - ./nps_server/conf/nps.conf:/nps/conf/nps.conf             
      