version: '3.7'

networks:
  dronenet:
    name: dronenet

services:
  nginx:
    image: nginx:alpine
    container_name: drone_nginx
    ports:
      - "8010:80"
    restart: always
    networks:
      - dronenet
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:rw
        
  gitea_server:
    image: gitea/gitea:latest
    ports:
      - 3000:3000
    volumes:
      - ./gitea_server/data:/data
    restart: always
    container_name: gitea_server
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - HTTP_PORT=3000
      - DB_TYPE=postgres
      - DB_HOST=gitea_postgres:5432
      - DB_USER=${POSTGRES_USER}
      - DB_NAME=${POSTGRES_DB}
      - DB_PASSWD={POSTGRES_PASSWORD}
      - APP_NAME="DROG (gitea + drone) test"
      # this exposes to end users
      - ROOT_URL=http://${HOST}:3000
    networks:
      - dronenet

  gitea_postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    restart: always
    container_name: gitea_postgres
    volumes:
      - ./gitea_postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - dronenet

  drone_mysql:
    image: mysql
    restart: always
    container_name: drone_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - dronenet
    volumes:
      - ./drone_mysql/conf/my.cnf:/etc/mysql/my.cnf:rw
      - ./drone_mysql/data:/var/lib/mysql/:rw
      - ./drone_mysql/logs:/var/log/mysql/:rw

  drone_server:
    image: drone/drone
    container_name: drone_server
    ports:
      - 8000:80 # drone comtainer serves via port 80, we expose to end users via port 8381
      # - 9000:9000
      # - 8443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone_server/data:/data:rw
      - ./drone_server/drone:/var/lib/drone:rw
    restart: always
    environment:
      # db Config
      - DRONE_DATABASE_DATASOURCE=${MYSQL_DATABASE}:${MYSQL_PASSWORD}@tcp(drone_mysql:3306)/drone?parseTime=true   #mysql配置，要与上边mysql容器中的配置一致
      - DRONE_DATABASE_DRIVER=mysql 

      - DRONE_TLS_AUTOCERT=false

      # gitea Config
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITEA_SERVER=http://${HOST}:3000 # this is internal communication with gitea server on the same network
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}  #RPC秘钥
      - DRONE_SERVER_HOST=${HOST}:8000
      - DRONE_SERVER_PROTO=http

      # droneclient Config

      # dronelog
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true
      - DRONE_LOGS_TEXT=true
    depends_on:
      - gitea_server
    networks:
      - dronenet

  droneagent:
    image: drone/agent:latest
    command: agent
    restart: always
    depends_on:
      - drone_server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_HOST=${HOST}:9000
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}  #RPC秘钥，要与drone_server中的一致
      - DRONE_RUNNER_CAPACITY=1
    networks:
      - dronenet