workspace:
  base: /go
  path: src/dronetest/

pipeline:
  测试:
    image: golang:alpine
    commands:
      - go test
  编译:
    image: golang:alpine
    commands:
      - go build
  镜像发布:
    image: plugins/docker
    repo: 192.168.0.90:8180/dronetest/testgo
    dockerfile: ./Dockerfile
    # context:
    # tags: latest
    auto_tag: true
    # auto_tag_suffix: linux-amd64
    registry: http://192.168.0.90:8180 # 如果使用自建的镜像仓库，例如 Harbor，这里可以通过 registry 指定
    secrets: [docker_username, docker_password] # 这里的用户名和密码在 web 界面指定
    # 启用不安全通讯,才能使用http
    insecure: true
    mirror: https://d8c5y6di.mirror.aliyuncs.com
    # 如果需要自动部署容器到服务器，可以打开下面这部分代码
  # deploy:
  #   image: appleboy/drone-ssh # 用于连接服务器
  #   host:
  #     - your_host
  #   username: your_name
  #   password: your_pass
  #   port: 22
  #   command_timeout: 300 # ssh命令行执行超时时间，300秒
  #   script:
  #     - docker pull repo_url:latest
  #     - docker rm -f docker-demo || true # 这里这样是因为如果不存在docker-demo，rm会报错
  #     - docker run -d -p 8065:8065 --name docker-demo repo_url
