version: "3.7"

services:
  postgres_update:
    image: tianon/postgres-upgrade:11-to-12
    container_name: postgres_update
    volumes:
      - /home/docker/drone_gitea_devops/gitea_postgres_old/data:/var/lib/postgresql/11/data
      - /home/docker/drone_gitea_devops/gitea_postgres/data:/var/lib/postgresql/12/data
    tty: true
    environment:
      - PGUSER=gitea
      - POSTGRES_INITDB_ARGS="-U gitea"
  # postgres_update:
  #   image: postgres:alpine
  #   container_name: postgres_update
  #   # restart: always
  #   volumes:
  #     # - ../gitea_postgres_old/bin:/usr/local/binold
  #     # - ../gitea_postgres_old/share:/usr/local/share/postgresqlold/
  #     # - ../gitea_postgres_old/data:/var/lib/postgresql/dataold
  #     - ../gitea_postgres/data:/var/lib/postgresql/data
  #   command: ["bash"]
  #   tty: true
  #   env_file: ../.env
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
