version: "3.7"

services:
  # gitea 可以用postgres也可以用mysql
  gitea_postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    restart: always
    container_name: gitea_postgres
    volumes:
      - ../gitea_postgres/data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    env_file: ../.env
